language: ruby
cache: bundler

matrix:
  include:
    - rvm: "1.8.7"
      gemfile: gems/minimum.gemfile
    - rvm: "1.9.3"
      gemfile: gems/minimum.gemfile
    - rvm: 2.0
    - rvm: 2.1
    - rvm: 2.2
    - rvm: 2.3
    - rvm: 2.4
    - rvm: 2.5
    - rvm: 2.6
    - rvm: 2.6
      name: rubocop yo
      script: bundle exec rubocop
    - rvm: 2.6
      gemfile: gems/minimum.gemfile
